# Generated by Django 5.0 on 2024-01-04 14:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, null=True, region=None, unique=True
            ),
        ),
    ]
