# Generated by Django 5.0 on 2024-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_number_of_cows",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "number_of_male_cows",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "number_of_female_cows",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "number_of_sold_cows",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "number_of_dead_cows",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
