# Generated by Django 4.2.7 on 2024-01-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Nutrition", "Nutrition"),
                            ("Infectious", "Infectious"),
                            ("Physiological", "Physiological"),
                            ("Genetic", "Genetic"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pathogen",
            name="name",
            field=models.CharField(
                choices=[
                    ("Bacteria", "Bacteria"),
                    ("Virus", "Virus"),
                    ("Fungi", "Fungi"),
                    ("Unknown", "Unknown"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
